### ISSUE TITLE
Main discussion

### ISSUE THREAD

**Issue by begarco** [WatchDogZZ/docs#1]
@pcolomb

**Comment by begarco** [comment]
L'intégration continue sur Travis CI est un peu étrange : certains build ne se lancent pas sur le repo 'android' et il y a un build random qui s'est lancé sur le repo 'server' où il n'y a pas de yaml d'ailleurs.

**Comment by pcolomb** [comment]
Votre console Travis est accessible ?

**Comment by begarco** [comment]
C'est sur travis-ci.org (version pour open source) : [https://travis-ci.org/WatchDogZZ](https://travis-ci.org/WatchDogZZ). Normalement en se connectant avec un compte GitHub on peut faire des trucs même si il y a pas grand chose de plus qu'en version public me semble-t-il.

**Comment by begarco** [comment]
Avancement sur le projet :
- Intégration sur Travis CI fonctionnelle
- Déploiement du jar Android sur GitHub Releases fonctionnel
- Tests sur Travis CI fonctionnel
- Création de 3 branches : dev, unittests et cisetup.
- Gantt initial

Question : faut-il détruire une branche après un pull-request accepté ou continuer à développer les nouvelles fonctionnalités dessus ?

**Comment by pcolomb** [comment]
Super !

A mon avis il faut creer une branche par pull request, ça permet d'avoir un nomage pertinent, de travailler facilement sur plusieurs features en même temps, etc ...

**Comment by begarco** [comment]
@BBS007 Le problème de déploiement de l'application Android est "résolu" par une copie de l'apk dans le dossier courant avant le déploiement :

```
before_deploy:
  - cp app/build/outputs/apk/app-release-unsigned.apk app-release.apk
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mTsN/cbIhI2WyJAh8ZiVqcdJLuda3grSZamglFHP0rPeSf33EWvX+6RB8sZuxnYrymxABOxMuXCekZZVqAN4maUFpddSc2uX3zUGh4zHWSOkl06rYSGwIS8nT0e2GUjAyQdSJ/ISoGf+tuau/dh/LaghHAa+pCwzxcqS/37mTNspkBoC9dRi4N9hg5AqJsjm89OCsr9wBoPipzPj6ywE47U+xln/+zhfSgkseWAdpFg4obV1sJR6Bxr/l+mDGZ9ozla+o/xvUOTTDIQrAqmLck45YPriuTjSsny+N5R6anNTMJiX9WjXNDvdShNXU2KOljodRE5YSA8ot4xr02z1bih9+o0i8SXZ5g/lDme5RLo44TBI9Kt9MmghmReuX/+SaB+NId45XCoqsIo667avBnzsXK2CxuzlGCAkAxncE81zIxUxbN0nXSpyIUYSOjxZJLz2AhdTZsF5OWy1Z7VH96BV6UatUh7EqiyOpcXaDHa1RDIH8X0OoK9rUWa4BuHM6CSWRV+olgblZaXT8AZ5thb7j9RyZZIwkHJ9v9r3u3sLaiBU1TAB2kl6/onVzJEFAB7AITi11ZzBbIDZ5j9HbPfa50p83bxInD6WZc72Q1RIsajVDA1V+n2IwhKaTjo/3lMpAlJMmcCwPJ1Td4RXWG5q6nSH0HZH7E4ZABc5aLQ=
  file: 
    - "app-release.apk"
  on:
    repo: WatchDogZZ/android
```

C'est pas génial d'autant plus que normalement `skip_cleanup: true` devrait suffire, mais ça fait le boulot. Je vais essayer d'avancer un maximum l'application Android ce week-end.
